---
- block:
    - apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - software-properties-common
        state: present

    - apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
        state: present
        update_cache: true

    - package:
        name: docker-ce
        state: present

#    - user:
#        name: "{{ docker_user }}"
#        groups: docker
#        append: yes
#      when: docker_user is defined
  become: yes
